(unless package--initialized (package-initialize t))

(add-to-list 'load-path "~/.emacs.d/configs")

(let ((file-name-handler-alist nil)
      (gc-cons-threshold most-positive-fixnum))
  (require 'packages)
  (require 'general)
  (require 'theme)
  (require 'editor)
  (require 'workflow)
  (require 'python-setup)
  (require 'clojure-setup)
  ;;(require 'haskell-setup)
  (require 'javascript-setup)
  (require 'web-setup)
  (require 'hotkeys)
  (require 'utility))

(setq custom-file "~/.emacs.d/custom.el")
(load custom-file 'noerror)
