;; -*- lexical-binding: t; -*-

;; Most leader-key overrides, but there are still others such as ace-window in ./init-workflow.el.

(define-key boat/leader-map (kbd "SPC") 'execute-extended-command)
(define-key boat/leader-map (kbd "TAB") 'evil-switch-to-windows-last-buffer)
(define-key boat/leader-map (kbd "/") 'consult-ripgrep)
(define-key boat/leader-map (kbd ";") 'evilnc-comment-operator)
(define-key boat/leader-map (kbd ",") 'evil-avy-goto-char)
(define-key boat/leader-map (kbd "u") 'universal-argument)
(define-key boat/leader-map (kbd "s") 'consult-line)
(define-key boat/leader-map (kbd "C-s") 'boat/consult-line-symbol)
(define-key boat/leader-map (kbd "h") 'help-command)

(define-prefix-command 'buffer-map)
(define-key boat/leader-map (kbd "b") 'buffer-map)
(define-key buffer-map (kbd "b") 'consult-buffer)
(define-key buffer-map (kbd "d") 'kill-current-buffer)
(define-key buffer-map (kbd "k") 'kill-buffer)
(define-key buffer-map (kbd "a") 'ibuffer)
(define-key buffer-map (kbd "n") 'next-buffer)
(define-key buffer-map (kbd "p") 'previous-buffer)
(define-key buffer-map (kbd "s") 'boat/goto-scratch)

(define-prefix-command 'file-map)
(define-key boat/leader-map (kbd "f") 'file-map)
(define-key file-map (kbd "f") 'find-file)
(define-key file-map (kbd "r") 'consult-recent-file)
(define-key file-map (kbd "s") 'save-buffer)
(define-key file-map (kbd "d") 'dired)
(define-key file-map (kbd "t") 'treemacs)
;; config-map exists within the file-map
(define-prefix-command 'config-map)
(define-key file-map (kbd "e") 'config-map)
(define-key config-map (kbd "d") 'boat/find-init-file)
(define-key config-map (kbd "R") 'boat/reload-init)

(define-prefix-command 'project-map)
(define-key boat/leader-map (kbd "p") 'project-map)
(define-key project-map (kbd "p") 'projectile-switch-project)
(define-key project-map (kbd "f") 'projectile-find-file)
(define-key project-map (kbd "b") 'consult-project-buffer)
(define-key project-map (kbd "s") 'consult-ripgrep)
(define-key project-map (kbd "C-s") 'boat/rg-thing-at-point)
(define-key project-map (kbd "d") 'projectile-find-file-in-directory)
(define-key project-map (kbd "r") 'projectile-replace-regexp)
(define-key project-map (kbd "k") 'projectile-kill-buffers)
(define-key project-map (kbd "t") 'treemacs-add-and-display-current-project-exclusively)
(define-key project-map (kbd "!") 'projectile-save-known-projects)
(define-key project-map (kbd ".") 'projectile-command-map)

(define-prefix-command 'git-map)
(define-key boat/leader-map (kbd "g") 'git-map)
(define-key git-map (kbd "s") 'magit-status)
(define-key git-map (kbd "b") 'magit-blame-addition)
(define-key git-map (kbd "d") 'magit-diff-buffer-file)
(define-key git-map (kbd "l") 'magit-log-buffer-file)
(define-key git-map (kbd "c") 'boat/review-changes)
(define-key git-map (kbd "r") 'boat/review-branch)

(define-prefix-command 'error-map)
(define-key boat/leader-map (kbd "e") 'error-map)
(define-key error-map (kbd "l") 'flycheck-list-errors)
(define-key error-map (kbd "n") 'flycheck-next-error)
(define-key error-map (kbd "p") 'flycheck-previous-error)
(define-key error-map (kbd "v") 'flycheck-verify-setup)

(define-prefix-command 'text-map)
(define-key boat/leader-map (kbd "m") 'text-map)
(define-key text-map (kbd "x") 'delete-trailing-whitespace)
(define-key text-map (kbd "i") 'indent-buffer)
(define-key text-map (kbd "t") 'toggle-truncate-lines)
(define-key text-map (kbd "p") 'prettier-js)
(define-key text-map (kbd "e") 'eval-buffer)

(define-key evil-window-map (kbd "d") 'evil-window-delete)
(define-key evil-window-map (kbd "m") 'delete-other-windows)
(define-key boat/leader-map (kbd "w") evil-window-map)

(define-prefix-command 'quit-map)
(define-key boat/leader-map (kbd "q") 'quit-map)
(define-key quit-map (kbd "q") 'save-buffers-kill-terminal)
(define-key quit-map (kbd "r") 'restart-emacs)

(provide 'init-hotkeys)
